# Assignment Questions

# 
1.Using Numpy to generate an array of 25 random numbers sampled from a standard normal distribution

In [1]:
import numpy as np
np.random.rand(25)

array([0.14635321, 0.81762441, 0.36665479, 0.62012242, 0.87160216,
       0.18745179, 0.66596684, 0.3801271 , 0.67631205, 0.5664124 ,
       0.83906995, 0.02637833, 0.29422823, 0.00445   , 0.22257828,
       0.03707497, 0.28045878, 0.5072496 , 0.34754383, 0.39962844,
       0.12556186, 0.07880396, 0.86839177, 0.25092558, 0.94533648])

In [2]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [3]:
import numpy as np
array = np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
print(array[[1,5,6]])

[[10 11 12 13 14 15 16 17 18 19]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]]


In [5]:
print(array[3:])

[[30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [6]:
print(array[0:10,3:8])

[[ 3  4  5  6  7]
 [13 14 15 16 17]
 [23 24 25 26 27]
 [33 34 35 36 37]
 [43 44 45 46 47]
 [53 54 55 56 57]
 [63 64 65 66 67]
 [73 74 75 76 77]
 [83 84 85 86 87]
 [93 94 95 96 97]]


In [7]:
print(array[2:5,1:8])

[[21 22 23 24 25 26 27]
 [31 32 33 34 35 36 37]
 [41 42 43 44 45 46 47]]


In [8]:
np.random.rand(100)

array([0.68603017, 0.8448594 , 0.11866477, 0.38102515, 0.03413112,
       0.03376649, 0.08353467, 0.33697635, 0.96877755, 0.71187258,
       0.65437317, 0.20308365, 0.22675822, 0.60470897, 0.31472737,
       0.97746465, 0.32149277, 0.79156515, 0.37580112, 0.81975605,
       0.46907303, 0.7984437 , 0.89453028, 0.41878327, 0.49306582,
       0.82204846, 0.18709547, 0.4736644 , 0.92266159, 0.5641736 ,
       0.02748495, 0.0604342 , 0.39836167, 0.5741493 , 0.76799561,
       0.68991165, 0.71127792, 0.12279917, 0.00177982, 0.55279434,
       0.92489199, 0.47675864, 0.58345821, 0.1274539 , 0.70149131,
       0.73785098, 0.25051528, 0.71651918, 0.80483858, 0.69530371,
       0.04578467, 0.72815485, 0.21362319, 0.57331173, 0.64090392,
       0.91687186, 0.20342738, 0.13216313, 0.97426078, 0.95694202,
       0.46411398, 0.23776943, 0.34605728, 0.04092992, 0.04076682,
       0.24516084, 0.0890745 , 0.85799681, 0.64975525, 0.71516149,
       0.84219555, 0.25288976, 0.67415405, 0.65523501, 0.23768

In [9]:
a = np.array([[7, 2], [5, 4]])
np.mean(a)

4.5

In [10]:
np.median(a)

4.5

In [11]:
np.std(a)

1.8027756377319946

In [12]:
a = np.array([[7, 1, 1, 7],
             [9, 4, 3, 8],
             [6, 1, 9, 7],
             [9, 7, 2, 5],
             [5, 1, 5, 9]])
a

array([[7, 1, 1, 7],
       [9, 4, 3, 8],
       [6, 1, 9, 7],
       [9, 7, 2, 5],
       [5, 1, 5, 9]])

In [13]:
from scipy import stats
stats.mode(a)

ModeResult(mode=array([[9, 1, 1, 7]]), count=array([[2, 3, 1, 2]]))